import process from 'node:process'
import { exec } from 'node:child_process'
import esbuild from 'esbuild'
import builtins from 'builtin-modules'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  plugins: [{
    name: 'rebuild-css',
    setup(build) {
      build.onEnd(() => {
        // eslint-disable-next-line no-console
        console.log('[rebuild-css] build CSS...')
        exec('npm run build:css')
      })
    },
  }],
})

if (prod) {
  await context.rebuild()
  process.exit(0)
}
else {
  await context.watch()
}
